# Generated by Django 4.2.3 on 2023-09-13 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loancontract',
            name='contract_file',
        ),
        migrations.AddField(
            model_name='loancontract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loancontract',
            name='status',
            field=models.CharField(default='en_attente', max_length=20),
        ),
    ]
