# Generated by Django 4.2.5 on 2023-09-17 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stageapp', '0002_remove_loancontract_contract_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePret',
            fields=[
                ('IdDemandePret', models.AutoField(primary_key=True, serialize=False)),
                ('DateDebut', models.DateField(null=True)),
                ('HDebut', models.TimeField(null=True)),
                ('DateFin', models.DateField(null=True)),
                ('HFin', models.TimeField(null=True)),
                ('PJDemande', models.TextField(null=True)),
                ('Exhibitor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
