# Generated by Django 4.2.5 on 2023-09-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0004_remove_loancontract_artwork_demandepret_artwork'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanContract',
        ),
    ]
